### ISSUE TITLE
Got Unknown Error Missing dependencies for SOCKS support

### ISSUE THREAD

**Issue by sxnfxsed** [realgam3/pymultitor#10]
Whenever I run the program I get this error after running "pymultitor -s --tor-cmd "C:/Tor/tor.exe" --on-count 25". I have requests and pysocks installed

07-07-17 02:34:56 ERROR    Got Unknown Error Missing dependencies for SOCKS support.

**Comment by realgam3** [comment]
It sounds like you didn't installed pymultitor dependencies (requirements.txt).

**Check it with:**
On Windows: `pip freeze | find "PySocks"`
On Linux: `pip freeze | grep PySocks`

If you don't see: **PySocks=={some version}** you need to install requirements.txt (see README)

**Comment by realgam3** [comment]
Fixed
