### ISSUE TITLE
TCP RST.

### ISSUE THREAD

**Issue by kokozaurz** [realgam3/pymultitor#13]
If and when for whatever reason theres a TCP reset (error - Got TCP Rst, While TCP Rst Not Configured), it still proceeds to do a request instead of trying to assign a new identity. This should be changed to drop the connection before the request is made and assign a new tor ip, otherwise it exposes the ip.

**Comment by realgam3** [comment]
You are right from some reason i changed it:
https://github.com/realgam3/pymultitor/commit/7ccf6e28060af6ea901875b08f14fa1562b31a01

**Comment by aerosadegh** [comment]
I test my code on Ubuntu 17.10 and not problem; But when i run my code on Centos 7, got this Error
`Got TCP Rst, While TCP Rst Not Configured`
Any idea?

**Comment by realgam3** [comment]
Please test the new version,
This issue will be open for the next 30 days.
