### ISSUE TITLE
Add HTTPProxy support

### ISSUE THREAD

**Issue by eromoe** [realgam3/pymultitor#15]
I mean tor command option HTTPProxy  https://www.torproject.org/docs/tor-manual.html.en .
Because many country ban tor,  I need connect tor network over another proxy

I tried `python pymultitor -c "tor -- HTTPProxy 127.0.0.1:1920"`, didn't wrok.

alter code to:
```
        self.process = launch_tor_with_config(
            config={
                "ControlPort": str(self.control_port),
                "SOCKSPort": str(self.socks_port),
                "DataDirectory": self.data_directory,
                "HTTPProxy ": "127.0.0.1:1920",
                "AllowSingleHopCircuits": "1",
                "ExcludeSingleHopRelays": "0",
            },
            tor_cmd=self.tor_cmd,
            init_msg_handler=self.print_bootstrapped_line
        )
```

neither work. .

**Comment by realgam3** [comment]
Good idea,
i will add option to extend configuration.

**Comment by therzv** [comment]
i also got some error.. cannot using with sqlmap.. got error connection
