### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by ghost** [realgam3/pymultitor#17]
Hello there.
1) when i set these options:
`options_dict = {
            'listen_host': "127.0.0.1",
            'listen_port': 7000,
            'ssl_insecure': True,
            'mode': "regular",
            'rawtcp': False,
            'auth_singleuser': auth
        }`
i still get NET::ERR_CERT_AUTHORITY_INVALID when i try to visit every site i want to browse. according to mitmproxy source:
`        except exceptions.ProtocolException as e:
           ...
            elif isinstance(e, exceptions.InvalidServerCertificate):
                self.log(str(e), "warn")
                self.log("Invalid certificate, closing connection. Pass --insecure to disable validation.", "warn")`
by setting `ssl_insecure `to True, these errors must vanish.
2) I also tried to set my tor browser to use this proxy, but it refuses to connect. for the tbb i have set mitmproxy as a socks5 proxy instead of regular, and specified this socks5 proxy both inside the browser and with these environment variables below; but it does not work:
`
SKIP_TOR_LAUNCH -> 1
TOR_SOCKS_PORT -> 7000
`
Thanks in advance.

**Comment by realgam3** [comment]
Please test the new version,
This issue will be open for the next 30 days.
