### ISSUE TITLE
pymultitor line 347 request erro

### ISSUE THREAD

**Issue by LKV19** [realgam3/pymultitor#30]
Hello I have a problem how can I fix this error?

127.0.0.1:51182: GET http://httpbin.org/ip
              << 200 OK 33b
127.0.0.1:51182: clientdisconnect
127.0.0.1:51184: clientconnect
15-01-21 17:49:24 ERROR    Got Unknown Error 'NoneType' object has no attribute 'socks_port'
Addon error: Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/PyMultitor-3.2.0-py3.6.egg/pymultitor.py", line 347, in request
    self.multitor.new_identity()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/PyMultitor-3.2.0-py3.6.egg/pymultitor.py", line 179, in new_identity
    self.current.newnym()
AttributeError: 'NoneType' object has no attribute 'newnym'

**Comment by SeungWookHan** [comment]
I think you should turn on Privoxy

**Comment by realgam3** [comment]
The issue is you have no tor process  running,
In the next version you will be able to get the error from the logs
and there will be less logs :)

**Comment by SeungWookHan** [comment]
> The issue is you have no tor process running,
> In the next version you will be able to get the error from the logs
> and there will be less logs :)

So Tor and Privoxy should be downloaded in local where this program to run right?
