### ISSUE TITLE
Example Explaination

### ISSUE THREAD

**Issue by dnminh11** [realgam3/pymultitor#5]
Hi, i'm using pymultitor and i'm lacking some knowledge in your example (https://github.com/realgam3/pymultitor/blob/blackhat/examples/on_string/bruteforce.py)
data={
'username': username,
'password': password,
},
Can you explain what 'username' and 'password' are?
Thank you.

**Comment by realgam3** [comment]
What you see is an example of use in script,
This username and password is not related to pymultitor its related to the bruteforce script.

**Comment by dnminh11** [comment]
I means are 'username' and 'password' the names of your website's elements? Because i tried to change it to suit with my website and it didn't work.

**Comment by realgam3** [comment]
its for the post data: username=x&password=y
its the post data parameters name, you can read more about it in:
http://docs.python-requests.org/en/master/user/quickstart/

**Comment by dnminh11** [comment]
I have a problem. My website is http://test.com/forum/login. After i post the data, the url redirects to */forum/login/login and prompt "Failed to login." so i can't check the content to verify the login details. Do you have any solutions?

**Comment by realgam3** [comment]
You can create callback in pymultitor + I'm using requests to send the requests and im checking every response,
Try to use pymultitor as a proxy to your browser if this issue still going send me more details if not you will need to rewrite your script.
