### ISSUE TITLE
Installing pymultitor in a virtualenv with latest pip version gets an error 

### ISSUE THREAD

**Issue by zerocool443** [realgam3/pymultitor#6]
Following error is observed : 

Could not find a version that satisfies the requirement pymultitor (from versions: )
No matching distribution found for pymultitor

Compiling  the source code works but installation with pip doesn't.

**Comment by zerocool443** [comment]
Looking at pip log : 

------------------------------------------------------------
/usr/bin/pip3 run on Mon Jun  5 16:55:37 2017
Downloading/unpacking pymultitor
  Getting page https://pypi.python.org/simple/pymultitor/
  Could not fetch URL https://pypi.python.org/simple/pymultitor/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/pymultitor/ when looking for download links for pymultitor
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for pymultitor:
  * https://pypi.python.org/simple/pymultitor/
  Getting page https://pypi.python.org/simple/pymultitor/
  Could not fetch URL https://pypi.python.org/simple/pymultitor/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/pymultitor/ when looking for download links for pymultitor
  Could not find any downloads that satisfy the requirement pymultitor
Cleaning up...
...........................

**Comment by realgam3** [comment]
Its a known issue, i will upload it to pip after BlackHat USA 2017 (https://www.blackhat.com/us-17/arsenal.html#pymultitor)

**Comment by zerocool443** [comment]
Thanks for updating the issue. And all the best wishes for your black hat 2k17 arsenal.
