### ISSUE TITLE
Error with lxml...

### ISSUE THREAD

**Issue by atao** [realgam3/pymultitor#7]
`Requirement already satisfied: stem>=1.5.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests<2.12.0,>=2.9.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Collecting mitmproxy<3.0.0,>=0.18.3 (from -r requirements.txt (line 4))
  Using cached mitmproxy-0.18.3-py2.py3-none-any.whl
Requirement already satisfied: hyperframe<5,>=4.0.1 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: h2<2.5,>=2.4.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: Flask<0.12,>=0.10.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: tornado<4.5,>=4.3 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: configargparse<0.12,>=0.10 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: pyperclip<1.6,>=1.5.22 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: certifi>=2015.11.20.1 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: Pillow<3.5,>=3.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: watchdog<0.9,>=0.8.3 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: urwid<1.4,>=1.3.1 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: pyasn1<0.2,>=0.1.9 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: cssutils<1.1,>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: passlib<1.7,>=1.6.5 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: click<7.0,>=6.2 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: html2text<=2016.9.19,>=2016.1.8 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: cryptography<1.6,>=1.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: construct<2.6,>=2.5.2 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Collecting lxml<=3.6.0,>=3.5.0 (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
  Using cached lxml-3.6.0.tar.gz
Requirement already satisfied: brotlipy<0.7,>=0.5.1 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: pyOpenSSL<17.0,>=16.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: pyparsing<2.2,>=2.1.3 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: six<1.11,>=1.10 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Collecting blinker<1.5,>=1.4 (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: enum34<2,>=1.0.4; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: backports.ssl-match-hostname<3.6,>=3.5.0.1 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: typing==3.5.2.2; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: ipaddress<1.1,>=1.0.15; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: jsbeautifier<1.7,>=1.6.3 in /usr/lib/python2.7/dist-packages (from mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: hpack<3,>=2.2 in /usr/lib/python2.7/dist-packages (from h2<2.5,>=2.4.1->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from Flask<0.12,>=0.10.1->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: Werkzeug>=0.7 in /usr/lib/python2.7/dist-packages (from Flask<0.12,>=0.10.1->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask<0.12,>=0.10.1->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: argh>=0.24.1 in /usr/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: pathtools>=0.1.1 in /usr/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/dist-packages (from cryptography<1.6,>=1.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.6,>=1.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.6,>=1.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Collecting editorconfig>=0.12.0 (from jsbeautifier<1.7,>=1.6.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: MarkupSafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask<0.12,>=0.10.1->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography<1.6,>=1.3->mitmproxy<3.0.0,>=0.18.3->-r requirements.txt (line 4))
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xuSjo_/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmplM7qMPpip-wheel- --python-tag cp27:
  Building lxml version 3.6.0.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
  creating build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/lxml
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
  In file included from src/lxml/lxml.etree.c:320:0:
  src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: Aucun fichier ou dossier de ce type
   #include "libxml/xmlversion.h"
                                 ^
  compilation terminated.
  Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit4w6Pcr.c -o tmp/xmlXPathInit4w6Pcr.o
  /tmp/xmlXPathInit4w6Pcr.c:1:26: fatal error: libxml/xpath.h: Aucun fichier ou dossier de ce type
   #include "libxml/xpath.h"
                            ^
  compilation terminated.
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, blinker, mitmproxy, editorconfig
  Found existing installation: lxml 3.6.4
    Uninstalling lxml-3.6.4:
      Successfully uninstalled lxml-3.6.4
  Running setup.py install for lxml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xuSjo_/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9ycHuu-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.6.0.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/sax.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/__init__.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
    creating build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-x86_64-2.7/lxml/includes
    creating build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-x86_64-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-x86_64-2.7/lxml/html
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-x86_64-2.7/lxml/isoschematron
    copying src/lxml/lxml.etree.h -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-x86_64-2.7/lxml
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-x86_64-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/rng
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-HVkOs2/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:320:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: Aucun fichier ou dossier de ce type
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit7pYdNC.c -o tmp/xmlXPathInit7pYdNC.o
    /tmp/xmlXPathInit7pYdNC.c:1:26: fatal error: libxml/xpath.h: Aucun fichier ou dossier de ce type
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of lxml
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xuSjo_/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9ycHuu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-xuSjo_/lxml/
`

**Comment by realgam3** [comment]
Again its not my issue :|
But you can install lxml from the wheel package:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
Install it with
`pip install lxml*.whl`

**Comment by atao** [comment]
I've an error... I use Kali Linux in Virtual Machine...

**Comment by realgam3** [comment]
sudo apt-get install libxml2-dev libxslt-dev python-dev

pip install lxml

**Comment by atao** [comment]
Thanks! It's work!
