### ISSUE TITLE
Stuck on Executing 2 Tor Processes

### ISSUE THREAD

**Issue by MazenElzanaty** [realgam3/pymultitor#8]
pymultitor
10-06-17 20:24:15 WARNING  Change IP Configuration Not Set (Acting As Regular Tor Proxy)
10-06-17 20:24:15 INFO     Executing 2 Tor Processes
 
and sometimes stuck on 
10-06-17 20:26:27 DEBUG    [51521] Tor Bootstrapped Line: Jun 10 20:26:27.000 [notice] Bootstrapped 0%: Starting
10-06-17 20:26:28 DEBUG    [51521] Tor Bootstrapped Line: Jun 10 20:26:28.000 [notice] Bootstrapped 5%: Connecting to directory server
10-06-17 20:26:28 DEBUG    [51521] Tor Bootstrapped Line: Jun 10 20:26:28.000 [notice] Bootstrapped 10%: Finishing handshake with directory server

**Comment by realgam3** [comment]
Did you check if you can execute tor directly?
Because some companies block tor servers....
